# Server
SERVER_SECTION_TOKEN = "SERVER"
SERVER_IP_TOKEN = "IP"
SERVER_PORT_TOKEN = "PORT"
TIME_WINDOW_TOKEN = "TIME_WINDOW"
SSL_KEY_FILE_TOKEN = "ssl_keyfile"
SSL_CERT_FILE_TOKEN = "ssl_certfile"

# Server Routes
SCORE_ENDPOINT_TOKEN = '//score'
FEEDBACK_ENDPOINT_TOKEN = '//feedback'

# Config
CONFIG_PATH_TOKEN = 'config.ini'
CONFIG_DEV_MODE_TOKEN = 'DEV'

# MONGO
MONGO_SECTION_TOKEN = 'MONGO'
MONGO_IP_TOKEN = 'IP'
MONGO_PORT_TOKEN = 'PORT'
MONGO_DB_TOKEN = 'DB'
MONGO_DB_DATA_TABLE_TOKEN = 'DATA_TABLE'
MONGO_DB_FEEDBACK_TABLE_TOKEN = 'USER_FEEDBACK_TABLE'
MONGO_DB_FUSION_TABLE_TOKEN = 'FUSION_ALERTS_TABLE'

# FUSION
DETECTORS_LIST = ['source_features', 'destination_features', 'rate_features', 'non group']

# FEEDBACK
FEEDBACK_SECTION_TOKEN = 'FEEDBACK'
BUDGET_TOKEN = 'BUDGET'

# FLOWS
FLOW_ID_TOKEN = 'flowid'
TIME_TOKEN = 'timestamp'
TIME_FORMAT = '%Y-%m-%d %H:%M:%S.%f'
MALICIOUS_TOKEN = 1
BENIGN = 0
